---
output:
  bookdown::pdf_document2:
    toc : no
    keep_tex: no
    number_sections: yes
---

\doublespacing

The following individuals certify that they have read, and recommend to the Faculty of Graduate
and Postdoctoral Studies for acceptance, the dissertation entitled:

\vspace{5mm}

\noindent\underline{\makebox[6in][l]{Transboundary fish stocks and their management under climate change}}  
\vspace{2mm}

submitted by \underline{Juliano Emmanuel Palacios Abrantes} in partial fulfillment of the requirements for

the degree of \noindent\underline{\makebox[5in][l]{Doctor of Philosophy}}  

in \noindent\underline{\makebox[5.8in][l]{Zoology}}

\vspace{5mm}

**Examining Committee:**

\noindent\underline{\makebox[6in][l]{William W.L. Cheung, Zoology, UBC}}  
Research Supervisor

\noindent\underline{\makebox[6in][l]{U. Rashid Sumaila, Institute for Resources, Environment and Sustainability, UBC}}  
Supervisory Committee Member 

\noindent\underline{\makebox[6in][l]{Les Lavkulich, Land and Food Systems, UBC}}  
University Examiner

\noindent\underline{\makebox[6in][l]{Scott Hinch, Forestry, UBC}}  
University Examiner

\noindent\underline{\makebox[6in][l]{Ellen K. Piktch, School of Marine and Atmospheric Sciences, Stony Brook University}}  
External Examiner



