---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

Under the United Nations Law of the Seas and the delineation of Exclusive Economic Zones (EEZs), fish stocks that cross neighbouring EEZs are known as transboundary stocks. The sustainability of these stocks depends on international cooperation. However, cooperation is faced with the challenges of insufficient understanding of where and how much fisheries resources are transboundary and climate change is shifting the distribution of marine species. My main objective is to understand the impacts of climate change-induced shifts on transboundary fish stocks distributions and their management, thereby informing international fisheries governance to prepare and respond to climate change. I rely on multiple data sources and numerical modelling to project species distributions under different scenarios of climate change.

I found that 67% of the species analyzed are transboundary and that between 2005 and 2014, fisheries targeting these species within global‐EEZs caught on average 48 million tonnes per year, equivalent to USD 77 billion in fishing revenue. As climate change alters ocean properties, the distribution of these species’ transboundary stocks are projected to shift to higher latitude, deeper waters or follow local environmental gradients. Specifically, 60% of the global transboundary stocks will have shifted beyond their historical distribution by 2020, and by 2075, all EEZs are projected to have a shifting transboundary stock. Moreover, the shared proportion of the catch of transboundary stocks between neighboring EEZs will change by 2030 relative to the historic proportion. The changes in the distribution and share proportion of transboundary stocks can potentially impacts the management of the related fisheries. For example, Canada and the United States manage important transboundary stocks. However, by 2050, the proportion of the total catch of some transboundary fish stocks shared between the two countries are expected to change relative to the present, even under a low greenhouse gas emissions scenario.

My findings improve our understanding about the current status of transboundary stocks and highlight the challenges that fisheries management will face in a changing climate. Finally, I identify potential adaptation options for transboundary fisheries management such as side payments, dynamic rules, and interchangeable quotas that can improve their sustainability under climate change.
