---
output:
  pdf_document:
    toc : no
    keep_tex: no
    number_sections: yes
---


```{r setup, eval = T, echo=F, warning=F, message=F, results='hide'}
library(MyFunctions)
#### Library ####
packages <- c(
  # "dplyr", # Data manipulation
  "knitr",
  "kableExtra"
)
my_lib(packages)
```



```{r glossary, eval = T, echo = F}

tibble(
   Abr =  c("IPHC",
            "UNCLOS",
            "UN",
            "FAO",
            "EEZ",
            "USD",
            "IPCC",
            "RCP",
            "RCP 2.6",
            "RCP 8.5",
            "SST",
            "PNA",
            "US",
            "EU",
            "RFMO",
            "ToE",
            "CI",
            "MSY",
            "MPA",
            "GFDL",
            "IPSL",
            "MPI",
            "MCP",
            "GoMA",
            "IOF",
            "UBC"
   ),
   Meaning = c(
      "International Pacific Halibut Commission", 
      "United Nations Law of the Sea",
      "United Nations",
      "Food and Agricultural Organization of the United Nations",
      "Exclusive Economic Zone",
      "United States Dollars",
      "Intergovernmental Panel on Climate Change",
      "Representative Concentration Pathway",
      "Representative Concentration Pathway (Low Emission Scenario)",
      "Representative Concentration Pathway (High Emission Scenario)",
      "Sea Surface Temperature",
      "Parties to the Nauru Agreement",
      "United States of America",
      "European Union",
      "Regional Fisheries Management Organization",
      "Time of Emergence",
      "Confidence Interval",
      "Maximum Sustainable Yield",
      "Marine Protected Area",
      "Geophysical Fluid Dynamics Laboratory Earth System Models 2M",
      "Institute Pierre Simon Laplace Climate Model 5",
      "Max Planck Institute for Meteorology Earth System Model",
      "Maximum Catch Potential",
      "Gulf of Maine Arrangement",
      "Institute for the Oceans and Fisheries",
      "University of British Columbia"
   )
) %>% 
   dplyr::arrange(Abr) %>%
   kable("latex",
   booktabs = T,
   col.names = NULL) %>%
   kable_styling(full_width = T) %>%
   column_spec(1, width = "2cm") %>%  # Size of first column
   column_spec(1, bold = T) # Abreviation bold

```