---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
header-includes:
  - \usepackage{setspace}
---
\doublespacing

I would like to start by acknowledging that this dissertation was mainly written in the traditional, ancestral, and unceded territory of the Musqueam People.

\vspace{5mm}


Many thanks to my adviser, William, for your brilliant guidance in this adventure, these were four years of smooth sailing! Thank you for your commitment and support to my professional development and for giving me so many opportunities. But also thank you for your kindness and humanity, you are certainly an inspiring person and a role model for current and future generations. I am very grateful to my committee members Daniel, Rashid and Villy for they support and advice. Special thanks to Rashid who was fundamental to many aspects of this dissertation, for keep pushing me to grow and do better, for trusting me, and for providing that spark of joy in our lives that we all need in the most troubled days. Rashid, I will keep pushing! Special thanks to Andrés Cisneros for all the insightful advice and guidance; to Gabriel Reygondeau for your patience in the multiple statistic discussions and for the football matches; and to Laura Rodríguez for your advice and support during this period. You are all truly inspiring people! Big shout-out to Colette Wabnitz, you are a wonderful human being and example to follow, thank you for all the unconditional support, the long discussions, and the advice in both my professional and personal life.

They say doing a PhD is a long and lonely path, I beg to differ. Colleagues and friends from CORU and from the IOF, this would not have been able without your friendship and support. Special shout-out to Ravi Maharaj for serving as a Vancouver ambassador, for all the numerous laughs, philosophical discussions and late nights shared over drinks decompressing from PhD anxieties; to Tanvi Vaidyanathan for your friendship and care for Niema; to my fearless leader Lian Kwong for inspiring me to be a better human and for all the help and support thorough the PhD process; to Samantha James for all those walks on campus that I so much miss; and Tim Cashion for making all those hard working days look easy. A mis queridos amigos del pescado Latino Americano, Rocío López, Santiago de la Puente, Luis Outeiro y Tayler Clarke, no es fácil estar lejos de casa y ustedes sin duda alguna hicieron el viaje más ameno. Friends outside the IOF, Gabrielle Menard, Bruna Silvestroni, Jeff Scott, Mauro Sugawara, Nicole Margot, Maite Erauskin, Pierre Rogy, Phil Underwood, Gerardo y Sarahí, and Hasasne Allegue, you guys were fundamental in keeping my sanity in these four years and I am truly grateful for all the amazing moments we shared. Bill French, Compa, thank you for making my Canadian experience more Mexican, for the laughs, and the camaraderie.

Lastly, this dissertation is the result of a 10-year long and winding road and its completion would not have been possible without the support of my family. Guillermo y Raquel, ustedes son mi pilar moral y modelo a seguir, gracias por apoyarme en todas mis decisiones, por más incoherentes que fueran; Martin gracias por siempre estar ahí para aconsejarme en las dicisiones más críticas. Angela e Amara, obrigado pela parceria e paciência no último ano do doutorado, vocês foram fundamentais na conclusão desste processo. Juliana Herrera, Renato Molina, Pablo Almuli, Mariano Palacios, Paula Bermudez, Luis Villegas, Diego Villegas, Maria Fernanda Sánchez, Mariela Sánchez, Osvaldo Morales, Rodolfo Hernández, Allan Tamallo, Delia Cuturiel, Severino Campos, Isabel Studer, Jean François, Tere Rojas, Luis Kandel, gracias por siempre estar ahí para apoyarme.


\vspace{5mm}

Juliano Palacios Abrantes

\vspace{10mm}

\begin{flushright}

No solo no [hubiéra] logrado nada sin ustedes
\linebreak
sino con toda la gente que estuvo a [mi] alrededor desde el comienzo;  
\linebreak
algunos siguen hasta hoy. ¡Gracias totales!  

\vspace{5mm}
- Gustavo Cerati

\end{flushright}