---
output:
  # word_document
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
header-includes:
    - \usepackage[utf8]{inputenc}
    - \usepackage[acronym]{glossaries}
    - \usepackage{wrapfig}
    - \usepackage{lipsum}
---

## Synthesis and Conclusion

In this dissertation, I endeavored to understand the impacts of climate change on transboundary fish stocks and their fisheries, with the objective of informing international fisheries management to prepare and respond to species on the move. Specifically, my dissertation focused on fish stocks that are shared between neighbouring Exclusive Economic Zones (EEZs). Managing such fish stocks often present a unique set of challenges for international fisheries management compared to other types of transboundary fisheries (Chapter 1). In this chapter, I synthesize the main findings from Chapters 2, 3, and 4, and provide a critical reflection on the importance of these findings and their uncertainties. Based on these findings, I identify a set of strategies for international fisheries management to cope with the changing climate. Finally, I propose some future research directions regarding climate change impacts on the management of transboundary marine stocks.


### Research contributions

Substantial uncertainty exists in the number of transboundary species since the delineation of EEZs by UNCLOS in the early 1980s (United Nations 1986, Miller and Munro 2002). Previous estimates range from 1500 taxa based on an informed guess (Caddy 1997), to 344 taxa based on a literature review (Teh and Sumaila 2015). Thus, to understand the impacts of climate change on transboundary fish stocks, I first determined what exploited marine fished species are actually transboundary, and more specifically, those that are shared by neighboring EEZs. In Chapter 2, I developed a methodology and collated and analyzed global ecological and fisheries data sets to provide a more robust estimate of the number of transboundary species that is based on available information on the biogeography and fisheries of exploited marine species. Such analysis identified a substantially higher number of global transboundary species compared to previous studies and suggested that we may have previously underestimated the importance of transboundary species to global fisheries catch and revenue. The updated estimates of the number of transboundary species and their importance in global and regional fisheries will contribute to the foundational knowledge for discussing fisheries management policies to achieve ocean sustainability under climate change. 

While substantial attention has been placed over the impacts of shifting stocks distributions to the management of marine resources [@Pinsky:2018cb; @Oremus:2020id], many questions remain unanswered regarding the risks of impacts of shifting transboundary stocks on their fisheries and the effectiveness of their management under climate change. In Chapter 3, I explored two specific aspects of the risks of impacts of shifting transboundary stocks: (1) the changes in the sharing of transboundary stocks between countries and (2) the time frame and intensity in which such changes will occur. These aspects of shifting transboundary stocks can help understand the challenges that climate change will bring to the management of transboundary fisheries [@Link:2010ei; @Gaines:2018sg]. I applied integrated climate-ocean-fish stock models and analyzed the model outputs through the lens of game theory in economics. I found that virtually all EEZs would experience at least one transboundary stock emerging by 2006 relative to the historical distribution (1951 - 2005). Consequently, the sharing proportion of several stocks have already shifted in at least one EEZ border. Moreover, the results highlight the high risk of impacts of climate change on transboundary management of the highly productive and economically important fisheries in small tropical EEZs. The results from this chapter can support international fisheries management anticipate the social-ecological consequences of shifting transboundary stocks and better prepare ocean governance in the face of climate change.

The risk of impacts of climate change on the management of transboundary fisheries will depend on the existing policies and specific international treaties [@Pinsky:2014by, Chapter 3]. Policies and treaties on transboundary fish stocks that lack a proper framework to address the consequences of shifting distributions of the fisheries resources can lead to international dispute and conflict, and drive unsustainable fishing activities [@Spijkers:2017ij; @Miller:2013iv; @Song:2017va; @Sumaila:2020tp]. In Chapter 4, I studied specifically two bi-lateral fisheries agreements between Canada and the United States: The International Pacific Halibut Commission that manages Pacific halibut (*Hippoglossus stenolepis*) and a resource sharing arrangement in the Gulf of Maine for cod (*Gadus morhua*), haddock (*Melanogrammus aeglefinus*) and yellowtail flounder (*Limanda ferruginea*). First, I examined the projected changes in relative sharing of these fish stocks under climate change (through the calculated stock share ratio described in Chapter 4). Second, I assessed the potential management consequences of the shifts in stock sharing. Finally, I explored examples of international fisheries governance that could potentially work in each of these two case study fisheries agreements. I showed that by 2050, the proportions of the catch of some of the jointly managed fisheries between Canada and the US are likely to change. Specifically, by 2050 Pacific halibut is expected to have moved poleward along the northeast Pacific coast and westward from the Gulf of Alaska to the Aleutian Islands and up to the Bering Sea under RCP 8.5. In the Gulf of Maine, climate change is expected to overall reduce the catch potential of cod, haddock and yellowtail flounder by 2050, regardless of the RCP. Here, changes in the stock share ratio will have different outcomes dependent on the climate change scenario and stock in question. For example, RCP 8.5 will affect Canada’s share of yellowtail flounder and haddock and increase cod share. From an ecological perspective, some frameworks seem to be more resilient to changes in fish stocks than others (i.e., quota is allocated following yearly samples and areas are closed to fishing). I identified that dynamic management that compensates fisheries in States with decreasing share of fish stocks through direct payment and/or interchangeable quotas are amongst the potential solutions for the adaptation of transboundary fisheries management under climate change in the North American region.

### Strategies for transboundary fisheries management under climate change

Based on the findings from this dissertation, I have identified a set of potential solutions to address the impacts of shifts in transboundary stocks distributions on their management under climate change. Overall, all of the identified solution options for international fisheries management will require cooperation between neighboring nations to generate adaptive, collaborative and equitable management strategies to address the uncertainties of a changing world [@Pinsky:2018cb; @Miller:2013iv; @Oremus:2020id; @Link:2010ei]. As I show below, dealing with shifting transboundary stocks to adjacent areas can be summarized in three main steps: (1) determine if distribution shifts of transboundary stock have occurred, (2) gather sufficient data on the stock's distribution and abundance, and (3) implement fisheries management that is adaptive to changing stocks, such as dynamic quota allocation and harvest controls [@Link:2010ei; @Twiname:2020jb; @Miller:2013iv]. 

#### Determining distributional shifts

Detecting distribution shifts of transboundary stocks requires monitoring of the populations, the environmental conditions of their habitats, and the fisheries that are exploiting these stocks  [@Link:2010ei; @Twiname:2020jb]. A multi-disciplinary and multi-institutional monitoring program is needed to gather data information on the biophysical, social-economic and governance aspects of transboundary fisheries [@Bonebrake:2017go].

Approaches to identify shifts in distributions of transboundary stocks include fisheries- independent and dependent surveys, citizen science, and monitoring of fishing activities. Fisheries-independent scientific surveys of fish stocks such as those undertaken by the IPHC are standardized and allow researchers to gather specific biological and oceanic information [@IPHC:2019wt, Chapter 4]. Moreover, scientific monitoring programs can help detect shifts in stocks biogeography, such as identifying range expansion of stocks to new areas [@Fogarty:2017eo]. However, scientific surveys are often expensive (e.g., the IPHC survey costs about USD $4 million annually), limiting the temporal and spatial coverage of such surveys. Many regions or countries also do not have the financial and technical capacity to undertake regular fisheries-independent scientific monitoring programs. In contrast, catch data analyses have been used to analyze shifting stocks among global EEZs as well as European regulatory areas [@Cheung:2013gk; @Baudron:2020dj]. Catch-data analyses are cheaper and provide longer time series and broader geographic range (e.g., FAO official catch statistics start in 1951 and include most coastal nations). However, the quality of catch data is affected by biases from the reporting methods, lack of specific geographic information and are dependent on fishing activities [@Pauly:2013gs; @Zeller2016]. 

Other methods of monitoring through interviews and "citizen science" can also provide information on shifting transboundary stocks. For example, in the East coast of the US, fishers have manifested the need to travel further into other States waters to "chase the fish" providing valuable information on shifts in stocks distribution by collecting information about fishing activities [@Pinsky:2012kq]. Moreover, in Australia, data collected by citizen science has been used in species distribution models to quantify range shifts [@Champion:2018gt]. Engaging in community-based monitoring such as citizen science, partnering up with fishing industries, and considering other disciplines as well as incorporating local ecological knowledge can provide valuable information to validate models and identify distributional shifts in transboundary fish stocks.
 
[^fis]:International Pacific Halibut Commission. Budget estimates for FY2020 and 2021. Available at:  https://iphc.int/uploads/pdf/am/2019am/ppt/iphc-2019-am095-18-p.pdf

#### Sharing data for resilient treaties

Having reliable, standardized, stock-level data is crucial to achieve sustainable fisheries management [@Hilborn:2014de]. Particularly, transboundary fish stocks management requires countries to monitor and share data about the fish stocks [@Pinsky:2018cb; @Miller:2013iv]. The effectiveness of such data sharing will be facilitated by protocols to standardize data collection and processing across EEZs. However, gaps in knowledge and capacity in monitoring fish stocks and fisheries between countries may pose barriers for the harmonization of data collection across countries. Such barriers are particularly apparent in the case of transboundary fish stocks shared between countries with different capacity e.g., Pacific sardine between Mexico and the US [@CisnerosMontemayor:2020kv]. Fostering more equitable international treaties that include support for capacity building and knowledge transfers between countries can help reduce such barriers in data sharing. Examples of international cooperation on knowledge and data transfer include regular international meetings such as the Mexico - US "Mexus" meetings [@NOAA:2018tu] and collaboration in the collection and sharing of data between neighboring countries such as the case between Canada and the US in the Gulf of Maine [@Miller:2013iv, Chapter 4]

### Adaptation of joint management to shifting stocks

Cooperation in the management of transboundary fish stocks is most likely to improve its effectiveness in achieving sustainable outcomes [@Bailey:2010ga; @Sumaila:2013hv]. However, the management of shared stocks requires countries to coordinate data collection, management actions, align conservation and extraction policies, and effectively implement the agreed policies [@Bailey:2010ga; @Sumaila:2013hv]. However, a recent analysis looking at total biomass over biomass required at maximum sustainable yield suggests that transboundary stocks are in worse shape than stocks that are only exploited in one EEZ  [@Liu:2020HI]. Climate change-induced stock distribution shifts will add additional challenge to the management of shared marine stocks (Chapters 2 and 3). Currently, most international treaties on transboundary fisheries management lack the mechanism to account for the shifts in stocks’ distributions and the associated responses by the fisheries [@Oremus:2020id; @Sumby:2021gw]. Creating alternative mechanisms that compensate one country by the other when shared stocks shift can motivate collaboration and improve the adaptability and resilience of current treaties [@Miller:2013iv; @Pinsky:2018cb; @Gaines:2018sg; @Oremus:2020id].

Fisheries management need to be more dynamic in nature to accommodate the increased uncertainties associated with the futures of fish stocks and fisheries under climate change [@Frolicher:2016dg] and be flexible enough to reduce the chance of causing international disputes caused by disagreement in managing fish stocks that are shifting their distributions [@Miller:2013iv; @Song:2017va; @Spijkers:2017ij]. Dynamic management is defined by Maxwell *et al.* [-@Maxwell2015] as "management that changes rapidly in space and time in response to the shifting nature of the ocean and its users based on the integration of new biological, oceanographic, social and/or economic data in near real-time." Some examples of dynamic management identified along this dissertation include yearly estimations of quota allocation, exchangeable quotas, MPAs with moving boundaries and changes in fishing areas (Chapters 3 and 4).

Quota allocation of shared stocks based on a fix-historical proportion like the case of the EU will be outdated as species shift their distribution [@Baudron:2020dj]. On the contrary, allocation strategies based on periodical estimations of stock distribution such as that of the IPHC for Pacific halibut (IPHC 2018) or a mix of historical and current distributions like in the Gulf of Maine (Chapter 4), should be able to adapt to shifts in stocks distributions. Similarly, cases like that of Norway and Russia in the Barents Sea  where a portfolio of stocks (and quota) can be exchangeable provide a way to deal with shifts in the distribution of shared stocks [@FAO:2020vw]. Marine Protected Areas are among the most popular tools in marine spatial management [@Song:2017iua]. However, their design mostly consists in fixed borders that ignore the stock's biogeography nor shifts [@FredstonHermann:2018kp; @Cashion:2020tw]. Solutions to this problem include the incorporation of dynamic protected areas like the fishing refuges in Mexico (Refugio Pesquero) where specific areas are temporary banned to fishing (e.g., 1 to 5 years) with the possibility of further expansion, re-location, and changes in protection level [@PescandoDatos:2020pd]. Different designs of MPAs like mobile, networks [@Cashion:2020tw], and transboundary [@Costello:2021bw] have also been identified as potential solutions for shifting stocks, and consequently, transboundary stocks management. However, more empirical evidence is needed to understand the potential of these tools [@FredstonHermann:2018kp; @Cashion:2020tw]. Other strategies of dynamic ocean management potentially applicable to transboundary stocks include programs that use real time (i.e., satellite) data tracking and align them with management, stock movement, and fisheries to aid in bycatch reduction [@Hazen:2018fa; @Howell:2008ii; @Hobday:2010ff; @Maxwell2015]. 

In addition to dynamic management, current agreements will need to become (more) resilient to the consequence of climate change to avoid discontinuity [@Miller:2013iv]. Setting the framework to include compensation methods (e.g., side payments) for when stocks shift between EEZs is one way to prepare for the uncertainty of the effects of climate change to stock's distributions [@Miller:2013iv; @Sumaila:2020tp]. Moreover, including criteria for newcomers to the fishery when the stock expands to new areas can also reduce the potential of conflict and undesired harvest levels [@Pinsky:2018cb]. While new and existing agreements will need to be adaptable, so that fisheries management can anticipate potential issues caused by shifting stocks or be more effective in dealing with disagreement between resource users.

### Limitations and uncertainties

Overall, this dissertation relies on global databases, climate change and species distributions projections, and climate change scenarios. These aspects contribute to the main sources of uncertainties associated with the analysis. In this section I describe the uncertainties related to these aspects while providing the general approach taken to address them.

#### Data and scale uncertainty

This dissertation uses data from diverse sources that have different inherent uncertainties and biases. Particularly, fisheries reconstructed catch data from the Sea Around Us and the ex-vessel price data form Tai et al. (2017) relies on several assumptions creating uncertainties in the estimations [@Pauly:2019bf; @Tai2017; @Zeller2016]. Regarding the Sea Around Us Catch database, while reconstructions address negative bias in reported catch, the estimation of such non-reported catch implies some level of uncertainty [@Pauly:2019bf]. For example, when data is not available for a year or a whole EEZ, the catch reconstruction method will extrapolate from previous years or estimates from parts of the EEZ. While this is not ideal, the method parts from the principle that "a best estimate is better than zero" when a fishery is known to exist [@Pauly:2019bf]. Similarly, price estimates are assigned by species within a country and when not available, similar species or neighbouring countries. Thus, it is not ideal to use this database for specific stocks, but rather large-scale regional and global analyses as I do in Chapters 2 and 3 [@Tai2017].

In total, I analyzed 938 marine species with different habitat preference and life history. Despite all of these species being marine, some of them are considered anadromus, that is, species like salmons (*Oncorhynchus sp.*) that spawn in fresh water (e.g., rivers) but spend most of their adult life in the ocean. In these cases, the models I used captured the oceanic life stage of the species but not the freshwater component. A recent study looking at climate change impacts on Chinook salmon (*Oncorhynchus tshawytscha*) at all life stages found that the freshwater stages of Chinook salmon is relatively resilient to climate change while large climate impacts are found in its marine stage [@Crozier:2021gd]. Thus, for some of the anadromous species, while my study did not consider the freshwater stage of these species, my results have captured the marine life stage where large climate impacts are expected to happen and where these impacts challenge transboundary management [@Crozier:2021gd;@Miller:2013iv; @Song:2017va].

In this dissertation I define a "fish stock" as a species within an EEZ (e.g., meta-population). Thus, I am not able to identify characteristics of transboundary stocks at finer resolutions (e.g., within an EEZ a species could have multiple stocks with only a subset of them transboundary; Chapter 2). This is important since management decisions based on conclusions from meta-populations could be erroneous as they could be ignoring key characteristics of sub-populations [@Kaplan:2016hs; @Archambault:2016ie]. This resolution affects mainly Chapters 2 and 3. Results from these chapters should be taken as a guidance to the potential impacts of climate change to transboundary fisheries management. More detailed research (e.g., at sub-stock level) will allow for less uncertain results better suited for management plans (See Future directions).

#### Modeling uncertainty

This dissertation integrates different modeling techniques to project species distributions under climate change. Models are representations of the reality that are based on available information and knowledge about the subject that the models represent. Therefore, models are subjected to uncertainties associated with assumptions, structure and data. My dissertation employed species distribution models (SDMs) as a main analytic tool. SDMs are numerical ways to determine associations between species geographic distributions and the environment, as well as the relationship of such association  [@Peterson:2012va]. Uncertainties associated with marine SDMs have been previously studied [@Beale:2012cs; @Araujo:2006bi] with some of them specific to their applications to study the impacts of climate change on species’ biogeography [@Goberville:2015bl; @Araujo:2007gf; @Heikkinen:2016jb; @Wiens:2009dj]. The uncertainties associated with SDMs that are particularly relevant to this dissertation include: the lack of or insufficient representation of the effects of species interactions [@Pecl:2017hu], evolutionary and/or epigenetic adaptation to environmental change, and other non-climatic anthropocentric factors [@Serpetti:2017he].

My dissertation's findings are also affected by uncertainties associated with the climate change projections from Earth system models. These uncertainties can be categorized into three main sources: *i*) model structure, *ii*) internal climate variability, and *iii*) different carbon emission scenarios [@Frolicher:2016dg; @Hawkins:2012hc]. 

(*i*) Model uncertainty is produced by the different ways models address fundamental environmental processes, in this case, regardless of the radiative forcing [@Frolicher:2016dg; @Bopp:2013fg]. As a result, different models can have divergent projections for a determined environmental variable (Chapter 4). Model uncertainty is examined in Chapters 2 and 4 by using projections from three ESMs.

(*ii*) Internal climate variability refers to the natural climate variation embedded in the Earth climate system (e.g., without considering radiative forcing). Such variation is mainly produced by large-scale events like El Niño-Southern Oscillation or the Atlantic Multidecal and Pacific Decadal Oscillations, although small-scale processes are also included [@Frolicher:2016dg]. In ESMs, climate variability is addressed by running multiple ensemble members, each one representing an initial condition of the Earth system [@Rodgers:2015jq; @Frolicher:2009ge]. Thus, the ESMs used in Chapters 2 and 4 represent the average of each ESM ensemble members. However, for Chapter 3 I used ten ensemble members of the GFDL ESM (i.e., ten runs of the same ESM). This allowed me to identify the climate change signal within the internal climate variability (See Chapter 3 Methods - Projecting species distributions under climate change).

(*iii*) Carbon emission scenarios represent the future pathways society can take in mitigating greenhouse gas emissions considering unknown technological and social factors [@Frolicher:2016dg]. These are commonly known as RCPs used by the IPCC to represent distinct potential futures of radiative forcing [@Gattuso:2015jz; @IPCC:2019tn]. The RCPs considered by the IPCC range from a "strong climate mitigation" (RCP 2.6) scenario to a "no mitigation" (RCP 8.5) scenario where society mainly relaxes greenhouse gases mitigation policies (See Introduction). In Chapter 4, I base my results on RCP 2.6 and RCP 8.5 capturing the main spectrum of future pathways currently considered by the IPCC. In Chapter 3, I only use outputs for RCP 8.5 scenario meaning that my results represent a "worst case" future scenario under climate change and that, any mitigation effort could reduce the intensity of the results.

### Future directions

I have identified neighbouring countries managing shared stocks (e.g., Norway and Iceland) with some cases of addressing environmental-driven shifts in species distributions (e.g., Canada and the U.S.). However, there is no complete database of management plans for shared stocks. Oremus *et. al.* (2020) developed a database of international treaties capturing 127 agreements in tropical waters. Building on the effort by Oremus et al. (2020), expanding the database to non-tropical regions while including key information such as managed species, the countries included in the treaty as well as the management rules placed could help answer key questions regarding the management of transboundary fisheries. Some of these key questions include the status of the stocks and its relationship to differences in level of cooperation in managing shared stocks between States, and the extent to which existing management plans are resilient to climate change resilience. This will allow us to have a better understanding of the current state of transboundary stocks and what management tools are potentially effective to address changes in stock distributions under climate change.

More work is needed to understand the effectiveness of dynamic management of transboundary stocks under climate change. Dynamic tools have been proved to be useful in the management of mobile marine resources [@Maxwell2015] and have been identified as a potential strategy for shifting distributions of shared stocks [@Gaines:2018sg; @Pinsky:2018cb; @Oremus:2020id]. However, most dynamic tools are yet to be tested under a climate change and transboundary fisheries framework, remaining as hypothetical solutions. Further development of models testing the functionality of different dynamic tools under climate change [@Cashion:2020tw] while also considering the nuisances of managing shared marine resources [@Costello:2021bw] could provide substantial advance to international ocean governance. Such research must be conducted under a multi-disciplinary framework to identify important trade-offs between the diverse set of societal values that social-ecological systems have. 

Further analyses should try to consider, when possible, spatially explicit biologically meaningful population units to inform local management. This is of specific concern for regions of the world where fisheries data is lacking like most fisheries in developing countries and many in developed countries. This dissertation considers a species within an EEZ as a stock, ignoring that discrete populations within a meta-population can have fundamental differences to management frameworks (See Limitations and uncertainties - Data and scale uncertainty). Reproducing the experiments that I conducted here considering biologically meaningful population units within neighbouring EEZs will likely provide managers with more confident results to base decisions. Such analysis, however, will require a set of local-scale baseline information, from population biology, to climate modeling, to economics of fishing, which are often missing. The further development of baseline scientific information at the local level can be supported by model-downscaling (e.g., the reduction of models' spatial resolution), and by including other sources of information such as citizen science [@AcevesBueno:2015hk], or multiple-source frameworks [@Zeller2016].

### Final remarks

The last eight months of this dissertation (and its formal defense) were written under a strict social-distancing and sometimes quarantine regime because of the 2020 COVID-19 pandemic. In many instances, the way to combat the COVID-19 pandemic is similar to that of climate change. To address both issues, we need global unification, science-based decision making, reduction of world inequality, and a global solidarization, specially of those more privilege with the most in need. The United Nations proclaimed that the next decade (2021-2030) will be focused on improving Ocean Science for Sustainable Development. Thus, we, as a global society, have the opportunity (and responsibility) to take action and improve fisheries management in the face of a changing climate. While the future is full of uncertainties, it is certain that the sustainability of transboundary fisheries in a changing world will only be achieved by following a multidisciplinary approach where concepts of ecology, conservation, economics, and social science are integrated and multiple societal values for nature are taken into consideration. Only then we will be able to achieve more equitable agreements, that benefit society as whole, rather than specific groups.


<!-- # Recycled text -->

<!-- ; the International Pacific Halibut Commission (IPHC) that manages Pacific halibut (*Hippoglossus stenolepis*) from Alaska to California, and an arrangement that provides management recommendations for cod (*Gadus morhua*), haddock (*Melanogrammus aeglefinus*) and yellowtail flounder (*Limanda ferruginea*) in the Gulf of Maine -->
