---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

Under the United Nations Law of the Seas (UNCLOS) and the delineation Exclusive Economic Zones (EEZs), fish (including invertebrates) stocks that cross national jurisdictions and the high seas are known as shared stocks. Specifically, shared stocks that distribute between neighboring countries EEZs are known as transboundary stocks while those that range between EEZs and the high seas are called straddling stocks. Theories and empirical evidence have shown that fisheries targeting resources that straddle between political boundaries complicate fisheries management and potentially reduce its effectiveness to achieve intended social, ecological and economic objectives. Cooperation between nations sharing the stocks will increase the likelihood of achieving these management objectives. However, enabling such international cooperation is faced with the challenges of the insufficient understanding of the where and how much fisheries resources are shared stocks. In addition, climate change alters the ocean conditions that drive shifts in species distributions. Cooperative management of shared stocks are less effective as the sharing of the stocks between countries are distributed, and in some cases, new shared stocks are created, under climate-induced species range shifts. The main objective of this dissertation is to understand the impacts of climate change on transboundary fish stocks and fisheries and their management, thereby informing international fisheries governance to prepare and respond to climate change.

In the second chapter, I estimate the global number of exploited marine species shared by neighboring countries and determine their contribution to global and regional catch and fisheries revenue. I use multiple data sources to overlay the known distribution of 938 commercially valuable marine species responsible for an average of 96.5% of global EEZ catch between 2005 and 2014, and 241 EEZs. The main findings show that 67% of the species analyzed are transboundary (n = 633) and that between 2005 and 2014, fisheries targeting these species within global‐EEZs caught on average 48 million tonnes per year, equivalent to an average of USD 77 billion in annual fishing revenue. For select countries, over 90% of their catch and economic benefits were attributable to a few shared resources while catch-data analysis suggests that catches from transboundary species are declining more than those from non‐transboundary species. This chapter has direct implications for managing fisheries targeting transboundary species, highlighting the need for developing effective and equitable international cooperation.

The third chapter looks at the effects of climate change on the distribution of the shared species identified in Chapter two. Specifically, I project future changes in the sharing of transboundary stock biomass between EEZs and the time (year) at when the decadal-mean changes in transboundary stock sharing exceed that of historical inter-annual variabilities. The shifts in international sharing of stock biomass are related to international conflicts in fisheries and periods of stock over-exploitation in the past. Using a dynamic species distribution model (Dynamic Bioclimate Envelope Model - DBEM) driven by ocean conditions simulated by three Earth system models, I project future shifts in stock sharing as an indicator of the risk of climate impacts on transboundary fisheries management. The results suggest that range shifts of 60% of shared species that are found in 87% of the world EEZs have emerged from historical variabilities. By 2075 all EEZs will have an emerging species, and by 2097, and all species will have emerged in at least one EEZ. Moreover, I show that the average proportion of shared species between neighboring EEZs will change between 1 and 10% with some exceeding 25% by 2030 relative to the historic proportion. These results suggest that most changes will happen before 2030 urging the adaptation of existing transboundary fisheries management policies, or the creation of new one in some cases, to account for shifts in the distribution of transboundary species due to climate change.

Finally, chapter four, I use Canada and the United States as a case study to explore the potential impacts that climate change will have on the management of transboundary stocks. Specifically, I examine the transboundary fish stocks and fisheries managed under the International Pacific Halibut Commission and a fisheries arrangement for the Gulf of Maine. I look at the current share proportion of each country and use the DBEM to see how this proportion will change under different warming scenarios. Results from this chapter show that, even under a low emission scenario, the proportion of the total catch of most fish stocks taken by a given country will change by 2050 relative to present. I identified that different mechanisms such as side payments, dynamic management, and interchangeable quotas could be employed to address such shifts and overcome the management challenges of shifting transboundary species.

Overall, findings from my dissertation improve our understanding about the current status of transboundary stocks in the world. The findings also highlight the challenges that management of shared stocks fisheries will face in a changing climate. Finally, my dissertation identifies potential adaptation options for transboundary fisheries management to improve their sustainability under climate change.
