---
output:
  # word_document
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
header-includes:
    - \usepackage[utf8]{inputenc}
    - \usepackage[acronym]{glossaries}
    - \usepackage{wrapfig}
    - \usepackage{lipsum}
---

## Synthesis and Conclusion

In this dissertation, I endeavored to understand the impacts of climate change on transboundary fish stocks and their fisheries, with the objective of informing international fisheries management to prepare and respond to species on the move. Specifically, my thesis focuses on fish stocks that are shared between neighbouring Exclusive Economic Zones (EEZs) that often present a unique set of challenges for international fisheries management compared to other types of transboundary fisheries (Chapter 1). Overall, I relayed upon on a diverse set of models projecting climate change and species distributions in the world oceans. Moreover, I synthesize data from several disciplines (e.g. fisheries, economics, and ecology) and incorporated spatial and multidisciplinary methodologies. In this section you will find a synthesis of the main findings from Chapters 2, 3, and 4, as well as a critical reflection on their importance and uncertainties. Based on these findings, I identify a set of strategies for international fisheries management to cope with the changing climate. Finally, I propose some future research directions regarding climate change impacts on the management of transboundary marine species.


### Research contributions

To understand the impacts of climate change on transboundary fish stocks, I first had to determine what marine fished species were actually transboundary, and more specifically, those that are shared by neighboring EEZs. However, substantial uncertainty exists in the number of transboundary species since the delineation of EEZs by UNCLOS in the early 1980s [@Munro:2002uf; @UnitedNations:1986tl]. Previous estimates based on an informed guess of the number of transboundary species in the world range from 500 to 1500 species [@Caddy:1997ue]. More recent estimate based on a literature review suggests 344 taxa  of transboundary species [@Teh:2015gd]. In Chapter 1, I developed a methodology and collated and analyzed global ecological and fisheries datasets to provide a more robust estimate of the number of transboundary species that is based on available information on the biogeography and fisheries of the exploited species. Such analysis identified a substantially higher number of global transboundary species compared to previous studies and suggested that we may have previously underestimated the importance of transboundary species to global fisheries catch and revenue. The updated estimates of the number of transboundary species and their importance in global and regional fisheries will contribute to the foundational knowledge for discussing fisheries management policies to achieve ocean sustainability under climate change. 

While substantial attention has been placed over the impacts of shifting stocks distributions to the management of marine resources [@Pinsky:2018cb; @Oremus:2020id], many questions remain unanswered regarding the risks of impacts of shifting transboundary stocks on their fisheries and the effectiveness of their management under climate change. In Chapter 2, I explored two specific aspects of the risks of impacts of shifting transboundary stocks: (1) the changes in the sharing proportion of transboundary stocks and (2) the time frame in which such changes will occur. These aspects of shifting transboundary stocks can help understand the challenges that climate change will bring to the management of transboundary fisheries [@Link:2010ei; @Gaines:2018sg]. I applied integrated climate-ocean-fish stock models and analyzed the model outputs through the lens of Game Theory in economics. according to the model, virtually all EEZs have had at least one transbounadry stocks emerging since 2006 relative to the historical distribution (1951 - 2005). Consequently, the sharing proportion of several stocks have already shifted in at least one EEZ border. Moreover, the results highlight the high risk of impacts of climate change on transboundary management of the highly productive and economically important fisheries in small tropical EEZs. The results from this chapter can support international fisheries management anticipate the social-ecological consequences of shifting transboundary stocks and better prepare ocean governance in the face of climate change.

The risk of impacts of climate change on the management of transboundary fisheries will depend on the existing policies and specific international treaties [@Pinsky:2014by, Chapter 3]. Policies and treaties on transboundary fish stocks that lack of a proper framework to address the consequences of shifting distributions of the fisheries resources can lead to international dispute and conflict, and drive unsustainable fishing activities [@Spijkers:2017ij; @Miller:2013iv; @Song:2017va; @Sumaila:2020tp]. In Chapter 4, I studied specifically two bi-lateral fisheries agreements between Canada and the United States: the International Pacific Halibut Commission that manages Pacific halibut (*Hippoglossus stenolepis*) and a resource sharing arrangement in the Gulf of Maine for cod (*Gadus morhua*), haddock (*Melanogrammus aeglefinus*) and yellowtail flounder (*Limanda ferruginea*). First, I examined the projected changes in relative sharing of these fish stocks under climate change (through the calculated stock share ratio described in Chapter 3). Second, I assessed the potential management consequences of the shifts in stock sharing. Finally, I explored examples of international fisheries governance that could potentially work in each of these two case study fisheries agreements. I show that by 2050, the proportions of the catch of some of the jointly managed fisheries between Canada and the US are likely to change. Specifically, by 2050 Pacific halibut is expected to have moved poleward along the northeast Pacific coast and westward from the Gulf of Alaska to the Aleutian islands and up to the Bering Sea under RCP 8.5. In the Gulf of Maine, climate change is expected to overall reduce the catch potential of cod, haddock and yellowtail flounder by 2050, regardless of the RCP. Here, changes in the stock share ratio of species will have different outcomes dependent on the climate change scenario and species in question. For example, RCP 8.5 will affect Canada’s share of yellowtail flounder and haddock and increase cod share. From an ecological perspective, some frameworks seem to be more resilient to changes in fish stocks than others (i.e., quota is allocated following yearly samples and areas are closed to fishing). I identified that dynamic management that compensates fisheries in States with decreasing share of fish stocks through direct payment and/orinterchangeable quotas are amongst the potential solutions for the adaptation of transboundary fisheries management under climate change in the North American region.

### Strategies for transboundary fisheries management under climate change

Based on the findings from this thesis, I have identified a set of potential solutions to address the impacts of shifts in transboundary species distributions on their management under climate change. Overall, all of the identified solution options for international fisheries management will require cooperation between neighboring nations to generate adaptive, collaborative and equitable management strategies to address the uncertainties of a changing world [@Pinsky:2018cb; @Miller:2013iv; @Oremus:2020id; @Link:2010ei]. As I show below, dealing with shifting transboundary stocks to adjacent areas can be summarized in three main steps: (1) determine if distribution shifts of transboundary species have occurred, (2) gather sufficient data on the stock's distribution and abundance, and (3) implement adequate rules such as dynamic quota allocation and harvest controls [@Link:2010ei; @Twiname:2020jb; @Miller:2013iv]. 

#### Determining distributional shifts

Detecting distribution shifts of transboundary stocks requires monitoring of the populations, the environmental conditions of their habitats as well as the fisheries that are exploiting these stocks  [@Link:2010ei; @Twiname:2020jb]. In addition to fisheries-independent scientific survey of fish stocks [@IPHC], fisheries-dependent catch data analyses have been used to detect shifting stocks [@Cheung:2013gk; @Baudron:2020dj] **[briefly comment on the pros and cons of these approaches].** Moreover, a multi-disciplinary and multi-institutional approach can also help address knowledge gaps related to shifting stocks in marine social-ecological systems. Specifically, such approahces are needed as such shifts will not only challange marine conservation, but also human well-being, environmental management and sustainable development [@Bonebrake:2017go]. For example, in the East coast of the US, fishers have manifest the need to travel further and further to "chase the fish" providing valuable information on shifts in species distribution [@Pinsky:2012kq]. 


Moreover, catch data analysis has been used to flag shifting species among global EEZs and European regulatory areas [@Cheung:2013gk; @Baudron:2020dj]. Evidence of shifts in species have also been done from ecological and conservation studies [@Fogarty:2017eo] and social science (e.g., citizen science [@REF]). Therefore, engaging in community-based monitoring such as citizen science, partnering up with fishing industries, and considering other disciplines as well as incorporating local ecological knowledge [@LEK] can provide valuable information to validate models and identify distributional shifts in transboundary fish stocks.

#### Sharing data for resilient treaties

Having reliable, standardized, stock-level data is crucial to achieve sustainable fisheries management [@Hilborn:2014de]. Particularly, transboundary fish stocks management requires countries to monitor and share data about the fish stocks [@Pinsky:2018cb; @Miller:2013iv]. The effectiveness of such data sharing will be facilitated by protocols to standardize data collection and processing across EEZs. However, gaps in knowledge and capacity in monitoring fish stocks and fisheries between countries may pose barriers for the harmonization of data collection across countries. Such barriers are particularly apparent in the case of transboundary fish stocks shared between countries with different capacity e.g., Pacific Sardine between Mexico and the US [@CisnerosMontemayor:2020kv]. Fostering more equitable international treaties that include support for capacity building and knowledge transfers between countries can help reduce such barriers in data sharing. Examples of international cooperation on knowledge and data transfer include regular international meetings such as the Mexico - US Mexus meetings [@NOAA:2018tu] and collaboration in the collection and sharing of data between neighboring countries such as the case between Canada and the US in the Gulf of Maine [@Miller:2013iv; Chapter 4]

### Adaptation of joint management to shifting stocks

Cooperation in management of transboundary fish stocks is most likely to improve its effectiveness in achieving sustainable outcomes [@Bailey:2010ga; @Sumaila:2013hv]. However, the management of shared stocks requires countries to coordinate data collection, management actions, align conservation and extraction policies, and effectively implement the agreed policies [@Bailey:2010ga; @Sumaila:2013hv]. Cooperation in management of transboundary fish stocks is most likely to improve its effectiveness in achieving sustainable outcomes [@Bailey:2010ga; @Sumaila:2013hv] requiring countries to coordinate data collection, management actions, align conservation and extraction policies, and effectively implement the agreed policies [@Bailey:2010ga; @Sumaila:2013hv]. However, a recent analysis looking at total biomass over biomass required at maximum sustainable yield suggests that transboundary stocks are in worst shape than stocks that are only exploited in one EEZ  [@Liu:2020HI]. Climate change-induced stock distribution shifts will add additional challenge to the management of shared marine stocks (Chapters 2 and 3). Currently, most international treaties on transboundary fisheries management lack the mechanism to account for the shifts in stocks’ distributions and the associated responses by the fisheries [@Oremus:2020id]. Creating alternative mechanisms that compensate one country by the other when shared stocks shift can motivate collaboration and improve the adaptability and resilience of current treaties [@Miller:2013iv; @Pinsky:2018cb; @Gaines:2018sg; @Oremus:2020id].

Fisheries management need to be more dynamic nature to accommodate the increased uncertainties associated with the futures of fish stocks and fisheries under climate change [@Frolicher:2016dg] and be flexible enough to reduce the chance of causing international disputes caused by disagreement in managing fish stocks that are shifting their distributions [@Miller:2013iv; @Song:2017va; @Spijkers:2017ij]. **Explain what dynamic management means here… ** 
Current agreements will need to become (more) resilient to the consequence of climate change to avoid discontinuity [@Miller:2013iv]. Setting the framework to include compensation methods (e.g. side payments) for when stocks shift between EEZs is one way to prepare for the uncertainty of the effects of climate change to stock's distributions [@Miller:2013iv; @Sumaila:2020tp]. Moreover, including criteria for newcomers to the fishery when the stock expands to new areas can also reduce the potential of conflict and undesired harvest levels [@Pinsky:2018cb]. While current agreements will need to adapt and flexibilize its structures, new agreements that are forged with these issues in mind are likely to anticipate potential issues caused by shifting species or be more effective in dealing with disagreement between users.


Moreover, exchangeable fishing quotas between a portfolio of species could provide more flexibility to countries to negotiate quota swaps between species. The reassessment of boundaries can also support transboundary fisheries management under a changing climate. This applies to both the stock (e.g., understanding where are the new boundaries of a stock; Link et al. 2010) but also to management tools such as areas closed to fishing (Chapter 4). Different designs of marine protected areas like shifting, networks, and transboundary[^molina] have also been identified as potential solutions for shifting stocks, and consequently, transboundary stocks management. However, more empirical evidence is needed to understand the potential of these tools [@FredstonHermann:2018kp; @Cashion:2020tw].

[^molina]:Molina R. & Costello C. Transboundary Marine Protected Areas, available at https://renatomolinah.com/research/

This thesis highlighted some existing examples of international transboundary fisheries that have dynamic management to deal with shifting stock distributions (Chapter 4). **For example, the joint management of the Pacific halibut through …. ** allocate quota based on yearly sampling of the population’s distribution across jurisdictions and spatially explicit stock assessments (Chapter 4) (Link et al. 2010, Pinsky and Mantua 2014). **A few more other examples of other types of dynamic management?**



### Limitations and uncertainties

Here I describe the main uncertainties that affect all chapters of my dissertation while providing the general approach taken to address them. Overall, this dissertation relys on global databases, climate change and species distributions projections and climate change scenarios. These aspects contribute to the main sources of uncertainties associated with the analysis.
AQUI


#### Data and scale uncertainty

Along this dissertation I rely on previously collected data from different sources that are not free of uncertainty. For example, fisheries catch data provided by the *Sea Around Us* provides different levels of uncertainty in reporting and allocating catch [@Pauly:2019bf], while the ex-vessel price data form Tai *et al* (2017) relies on several assumptions creating uncertainties in the estimations. Moreover, the ecological scale of my analyzes is at the species level, rather than a genetically or morphological distinct units (e.g. "stocks") [@Nelson:2016kk] due to a lack of spatially explicit information for most species included in this study. This resolution affects mainly chapters 2 and 3.

Because data are at a species level, I was not able to identify the actual contribution of the transboundary stock to catch and revenue, despite applying methods to limit a potential overestimation (Chapter 2 - Methods). Moreover, there is criticism associated with management decisions based on conclusions from meta-populations [@Kaplan:2016hs; @Archambault:2016ie]. For Chapter 4, while Pacific halibut is considered as one single stock, the shared stocks in the Gulf of Maine might have different life history values than those used for the species from *FishBase* affecting the DBEM outputs. Therefore, the results presented in this dissertation should be taken as a guidance to the potential impacts of climate change to transboundary fisheries management, urging for more detailed research for the elaboration of better-suited management plans. 

#### Modeling uncertainty

This dissertation is based on different modeling techniques. Models are representations of the reality that are based on available information and knowledge about the subject that the models represent, and are thus subject to uncertainties associated with model assumptions, structure and data. As such, the results of this dissertation are also subjected to different types of uncertainties. My thesis employed species distribution models (SDMs) as a main analytical tool. SDMs are numerical ways to determine associations between species geographic distributions and the environment, as well as the relationship of such association  [@Peterson:2012va]. Uncertainties associated with marine SDMs have been previously studied [@Beale:2012cs; @Araujo:2006bi] with some of the uncertainties are specific to their applications to study the impacts of climate change on species’ biogeography [@Goberville:2015bl; @Araujo:2007gf; @Heikkinen:2016jb; @Wiens:2009dj]. The uncertainties associated with SDMs that are particularly relevant to this dissertation include: the lack of or insufficient representation of the effects of species interactions [@Pecl:2017hu], evolutionary and/or epigenetic adaptation to environmental change, and other non-climatic anthropocentric factors [@Serpetti:2017he].

My thesis findings are also affected by uncertainties associated with the climate change projections from Earth system models. These uncertainties can be categorized into three main sources: *i*) model structure, *ii*) internal climate variability, and *iii*) different carbon emission scenarios (Hawkins and Sutton 2012, Frölicher et al. 2016). [@Frolicher:2016dg; @Hawkins:2012hc]. 

(*i*) Model uncertainty is produced by the different ways models address fundamental environmental processes, in this case, regardless of the radiative forcing [@Frolicher:2016dg; @Bopp:2013fg]. As a result, different models can have divergent projections for a determined environmental variable (Chapter 4, Figure \ref{fig:FigureS21}). Model uncertainty is examined in Chapters 2 and 4 by using projections from three ESMs.

(*ii*) Internal climate variability refers to the natural climate variation embedded in the Earth climate system (e.g. without considering radiative forcing). Such variation is mainly produced by large-scale events like El Niño-Southern Oscillation or the Atlantic Multiddecal and Pacific Decadal Oscillations, although small-scale processes are also included [@Frolicher:2016dg]. In ESMs, climate variability is addressed by running multiple ensemble members, each one representing a initial condition of the Earth system [@Rodgers:2015jq; @Frolicher:2009ge]. Thus, the ESMs used in Chapters 2 and 4 represent the average of each ESM ensemble members. However, for Chapter 3 I used ten ensemble members of the GFDL ESM (e.g. ten runs of the same ESM). This allowed me to identify the climate change signal within the internal climate variability (See Chapter 3 Methods - Projecting species distributions under climate change).

(*iii*) Carbon emission scenarios represent the future pathways society can take in mitigating greenhouse gas emissions considering unknown technological and social factors [@Frolicher:2016dg]. These are commonly known as RCPs used by the IPCC to represent distinct potential futures of radiative forcing [@Gattuso:2015jz; @IPCC:2019tn]. The RCPs considered by the IPCC range from a "strong climate mitigation" (RCP 2.6) scenario to a "no mitigation" (RCP 8.5) scenario where society mainly relaxes greenhouse gases mitigation policies (See Introduction). In Chapter 4, I base my results on RCP 2.6 and RCP 8.5 capturing the main spectrum of future pathways currently considered by the IPCC. In Chapter 3, I only use outputs for a RCP 8.5 scenario meaning that my results represent a "worst case" future scenario under climate change and that, any mitigation effort could reduce the intensity of the results.

### Future directions

I have identified neighbouring countries managing shared stocks (e.g. Norway and Iceland) with some cases of addressing environmental-driven shifts in species distributions (e.g. Canada and the U.S.). However, there is no complete database of management plans for shared stocks. Oremus *et. al.* (2020) have developed a database of international treaties capturing 127 agreements in tropical waters. Building on the effort by Oremus et al., a database that include **x, y z…**could help answer key questions regarding the management of transboundary fisheries. Some of these key questions include the status of the stocks and its relationship to differences in level of cooperation in managing shared stocks between States, and the extent to which existing management plans are resilient to climate change resilience. This will allow us to have a better understanding of the current state of transboundary stocks and what management tools are potentially effective to address changes in stock distributions under climate change.

Dynamic management tools are potentially effective in dealing with shifting distributions [@Gaines:2018sg; Chapters 2, 3 and 4]. However, many of these tools are yet to be tested remaining as hypothetical solutions (Cashion *et. al.*, n.d.).^[Molina R. & Costello C. Transboundary Marine Protected Areas, available at https://renatomolinah.com/research/] Further development of models and empirical exercises testing the functionality of different dynamic tools will mean a substantial advance in the management of shared stocks under a changing world. Such experiments, if conducted under a multi-disciplinary framework, will allow to find important tradeoffs between a diverse set of societal values, and thus, providing more resilient strategies (Palacios-Abrantes *et al.*, n.d.).

Stock level analysis will be better suited to inform local management. As previously mentioned, this dissertation focuses at the species level, ignoring that discrete populations within a meta-population can have fundamental differences to management frameworks (See Limitations and uncertainties - Data and scale uncertainty). Reproducing the experiments that I conducted here at the stock level will likely provide managers with more confident results to base management decisions. Such analysis, however, will require a set of local-scale baseline information, from population biology, to climate modeling, to economics of fishing, often missing. The further development of baseline scientific information at the local level can be supported by model-downscaling (e.g. the reduction of models' spatial resolution), and by including other sources of information such as citizen science [@AcevesBueno:2015hk], or multiple-source frameworks [@Zeller2016].

### Final remarks

The last eight months of this dissertation were written under a strict social-distancing and sometimes quarantine regime because of the 2020 COVID-19 pandemic. In many instances, the way to combat the COVID-19 pandemic is similar to that of climate change. To address both issues, we need global unification, science-based decision making, reduction of world inequality, and a global solidarization, specially of those more privilege with the most in need. The United Nations proclaimed that the next decade (2021-2030) will be focused on improving Ocean Science for Sustainable Development. Thus, we, as a global society, have the opportunity (and responsibility) to take action and improve fisheries management in the face of a changing climate. While the future is full of uncertainties, it is certain that the sustainability of transboundary fisheries in a changing world will only be achieved by following a multidisciplinary approach where concepts of ecology, conservation, economics, and social science are integrated and multiple societal values for nature are taken into consideration. Only then we will be able to achieve more equitable agreements, that benefit society as whole, rather than specific groups.


<!-- # Recycled text -->

<!-- ; the International Pacific Halibut Commission (IPHC) that manages Pacific halibut (*Hippoglossus stenolepis*) from Alaska to California, and an arrangement that provides management recommendations for cod (*Gadus morhua*), haddock (*Melanogrammus aeglefinus*) and yellowtail flounder (*Limanda ferruginea*) in the Gulf of Maine -->
