---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
header-includes:
   - \usepackage{ragged2e}
   - \usepackage{setspace}
---

\thispagestyle{empty}
\begin{singlespace} 
\begin{center}

\Huge

\textbf{TRANSBOUNDARY FISH STOCKS AND THEIR MANAGEMENT UNDER CLIMATE CHANGE}

\Large

\vspace{8mm}

by

\vspace{8mm}

\huge

Juliano Emmanuel Palacios Abrantes  

\Large

\vspace{8mm}

B.Sc. Universidad Autonoma Metropolitana unidad Xochimilco, Mexico City, Mexico, 2012  

M.Sc. University of California at Santa Barbara, Santa Barbara California, US, 2016  

\vspace{10mm}

A DISSERTATION SUBMITTED IN PARTIAL FULFILLMENT OF THE REQUIREMENTS FOR THE DEGREE OF

\vspace{5mm}

DOCTOR OF PHILOSOPHY

\vspace{5mm}
in

\vspace{5mm}

THE FACULTY OF GRADUATE AND POSTDOCTORAL STUDIES

\vspace{5mm}

(Zoology)

\vspace{5mm}

THE UNIVERSITY OF BRITISH COLUMBIA

\vspace{5mm}

(Vancouver)

\vspace{6mm}

[exp.2020]

© Juliano Emmanuel Palacios Abrantes  

\end{center}
\end{singlespace}
\normalsize
\clearpage
