---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

Climate change is changing the composition of the ocean. The water is warming, the dissolved oxygen  available is decreasing and the water is increasing in acidity. As a consequence, marine fish species have been shifting their distribution looking for a more suitable habitat compromising the management of fisheries that fail to take into consideration such shifts. This is of specific concern to fish species that straddle the political boundaries of neighboring countries, also known as transboundary species. Here, I aim to understand how will climate-change-driven shifts in species distribution affect the management of international shared species. I relay on a combination on numerical models to project future oceanic conditions and species distributions. Moreover, I consider two possible scenarios of warming to identify and quantify future's uncertainty. Finally, I integrate different components of fisheries social-ecological system by combining a set of multi-disciplinary approaches from ecology, to economics, to fisheries science. Two main findings emerge from my dissertation (*i*) The importance of transboundary species have been previously underestimated and require special attention in terms of management under a changing climate, and (*ii*) a substantial amount of transboundary stocks have already shifted their distribution globally and many more are expected to change in the incoming years urging managers to take these shifts into consideration. The main conclusion of my thesis is that the incorporation of dynamic management could help reduce the negative impacts of climate change on the management of transboundary fisheries.


