---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

I am the main author of all chapters and lead author of all papers resulting from this work. I took primary responsibility for the research contained in the chapters, including the design, data collection, analysis and writing. This was done under the guidance of my supervisor Dr. William W.L. Cheung, and my committee members Dr. Daniel Pauly, Dr. U. Rashid Sumaila, and Dr. Villy Christensen. Moreover, Each chapter has different co-authors that played a critical role in the development of the studies providing their expertise and advice with ideas, methods and data interpretation. Some of the chapters of this dissertation have been published or submitted for publication as stated below.

A version of Chapter Two is currently *Under review* at a peer review journal. In this chapter I did the conceptualization, developed the methodology, performed the formal analysis and wrote the original draft. Gabriel Reygondeau supported the methodology, did the data curation, and contributed to the writing, reviewing and editing of the final draft. Colette Wabnitz supported the methodology, and contributed to the writing, reviewing and editing of the final draft. William Cheung did the supervision, and contributed to the writing, reviewing and editing of the final draft. The working title of this chapter is: 

- *Marine species do not need visas: the transboundary nature of the world’s exploited marine species.* Juliano Palacios-Abrantes, Gabriel Reygondeau, Colette Wabnitz, and William W.L. Cheung

A version of chapter two is being prepared for submission to a peer review journal. I did the conceptualization, co-developed the methodology, performed the formal analysis and wrote the original draft. Thomas Frölicher and William Cheung helped develop the methods, William Cheung supported the conceptualization, did the supervision, and contributed to the writing, reviewing and editing of the final draft. Rashid Sumaila, Gabriel Reygondeau, and Colette Wabnitz contributed to the writing, reviewing and editing of the final draft. The working title of this chapter is: 

- *Matching the time of emergence of transboundary fish stocks to lead time for policy response under climate change.* Juliano Palacios-Abrantes, Thomas Frölicher, U. Rashid Sumaila, Gabriel Reygondeau, Colette Wabnitz, and William W.L. Cheung.

Chapter three has been accepted at the peer journal *Ecology & Society* as part of the special issue *[INSERT NAME]*. For this chapter I developed the methodology, performed the formal analysis, and wrote the original draft. Rashid Sumaila and William Cheung supported the conceptualization of the study and and contributed to the writing, reviewing and editing of the final draft. The reference for this paper is as follows: 

- Palacios-Abrantes, J. U. Sumaila R., and Cheung W.W.L. 2020. Challenges to transboundary fisheries management in North America under climate change. *Ecology & Society*, [in press].

In addition to the chapters here mentioned, I directly contributed to two studies directed related to my dissertation. In the Pinsky *et al., 2018* paper I co-developed the methodology and contributed to the writing, reviewing and editing of the final draft. The Sumaila *et al., in press* paper is an extension of the Chapter Four of this dissertation where we look at the economic implications of management of transboundary fish stocks under climate change. The reference for these papers are as follows: 

- Pinsky, M. L., Reygondeau, G., Caddell, R., Palacios-Abrantes, J., Spijkers, J., and Cheung, W. W. L., 2018. Preparing ocean governance for species on the move. *Science*, 360 (6394), 1189–1191.

- Sumaila, U.R., Palacios-Abrantes, J., and Cheung, W.W.L. Climate change, shifting threat points and the management of transboundary fish stocks *[In press]*
